spring.application.name=hello-world-auth
server.port=8080
logging.level.com.example.hello_world_auth=DEBUG

# JWT Configuration
jwt.secret=yourSecretKeyHereMustBeAdsdsdsdtLeast32CharsLongForSecurity111111dsdsdsdsdsdsdsdsdsds111